# 航点到达容忍距离(m)
tolerance_waypoint: 0.1

#追踪参数
trace_center_x: 320
trace_center_y: 320
cam_loc_rate: 0.001
aim_high_trace: 0.1
tolerace_pix: 10
step_size_trace: 0.1
pickup_center_x: 320
pickup_center_y: 320
pickup_aim_high: 0.1
pickup_step_size: 0.1

# 话题参数
MAV_state: "/mavros/state"
MAV_localPositionPose: "/mavros/local_position/pose"
MAV_cmdArming: "/mavros/cmd/arming"
MAV_setMode: "/mavros/set_mode"
MAV_setpointPositionLocal: "/mavros/setpoint_position/local"
CAM_info: "/cam_tracker/info"

#航点参数
takeoff_waypoint_v: [0.0, 0.0, 2.0]
pickup_start_waypoint_v: [1.0, 0.0, 1.0]
pickup_end_waypoint_v: [0.0, 1.0, 1.0]
avoid_start_waypoint_v: [1.0, 1.0, 1.0]
avoid_end_waypoint_v: [0.0, 1.0, 1.0]
trace_start_waypoint_v: [1.0, 1.0, 1.0]
trace_end_waypoint_v: [0.0, 1.0, 1.0]
