# 航点到达容忍距离(m)
tolerance_waypoint: 0.1

# 起飞点坐标（相对home点）
takeoff_pose_x: 0.0
takeoff_pose_y: 0.0
takeoff_pose_z: 1.0  # 起飞高度设为2m（默认值）

# 拾取点坐标（相对home点）
pickup_start_pose_x: 1.0
pickup_start_pose_y: 0.0
pickup_start_pose_z: 1.0
pickup_end_pose_x: 0.0
pickup_end_pose_y: 1.0
pickup_end_pose_z: 1.0

# 避障点坐标（相对home点）
avoid_start_pose_x: 1.0
avoid_start_pose_y: 1.0
avoid_start_pose_z: 1.0
avoid_end_pose_x: 0.0
avoid_end_pose_y: 1.0
avoid_end_pose_z: 1.0

# 追踪点坐标（相对home点）
trace_start_pose_x: 1.0
trace_start_pose_y: 1.0
trace_start_pose_z: 1.0
trace_end_pose_x: 0.0
trace_end_pose_y: 1.0
trace_end_pose_z: 1.0