# 航点到达容忍距离(m)
tolerance_waypoint: 0.1

# 起飞点坐标（相对home点）
takeoff_pose_x: 0.0
takeoff_pose_y: 0.0
takeoff_pose_z: 1.0 # 起飞高度设为2m（默认值）

# 拾取点坐标（相对home点）
pickup_start_pose_x: 1.0
pickup_start_pose_y: 0.0
pickup_start_pose_z: 1.0
pickup_end_pose_x: 0.0
pickup_end_pose_y: 1.0
pickup_end_pose_z: 1.0

# 避障点坐标（相对home点）
avoid_start_pose_x: 1.0
avoid_start_pose_y: 1.0
avoid_start_pose_z: 1.0
avoid_end_pose_x: 0.0
avoid_end_pose_y: 1.0
avoid_end_pose_z: 1.0

# 追踪点坐标（相对home点）
trace_start_pose_x: 1.0
trace_start_pose_y: 1.0
trace_start_pose_z: 1.0
trace_end_pose_x: 0.0
trace_end_pose_y: 1.0
trace_end_pose_z: 1.0

#追踪参数
trace_center_x: 320
trace_center_y: 320
cam_loc_rate: 0.001
aim_high_trace: 0.1
tolerace_pix: 10
step_size_trace: 0.1
pickup_center_x: 320
pickup_center_y: 320
pickup_aim_high: 0.1
pickup_step_size: 0.1

# 话题参数
MAV_state: "/mavros/state"
MAV_localPositionPose: "/mavros/local_position/pose"
MAV_cmdArming: "/mavros/cmd/arming"
MAV_setMode: "/mavros/set_mode"
MAV_setpointPositionLocal: "/mavros/setpoint_position/local"
CAM_info: "/cam_tracker/info"

#航点参数
takeoff_waypoint_v: [0.0, 0.0, 1.0]
pickup_start_waypoint_v: [1.0, 0.0, 1.0]
pickup_end_waypoint_v: [0.0, 1.0, 1.0]
avoid_start_waypoint_v: [1.0, 1.0, 1.0]
avoid_end_waypoint_v: [0.0, 1.0, 1.0]
trace_start_waypoint_v: [1.0, 1.0, 1.0]
trace_end_waypoint_v: [0.0, 1.0, 1.0]
